[workspace]
authors = ["jawadad <alaaedeenjawad@gmail.com>"]
channels = ["conda-forge"]
name = "napari"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.10"
ipykernel = ">=7.3.0,<8"
jupyter = ">=1.1.1,<2"
setuptools = "<82"

[pypi-dependencies]
scimap = { version = ">=2.3.6, <3", extras = ["napari"] }
anndata = ">=0.10.9, <0.11"
tifffile = ">=2023.12.9, <2024"
