[workspace]
authors = ["jawadad <alaaedeenjawad@gmail.com>"]
channels = ["conda-forge"]
name = "niches_clustering"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
r-base = ">=4.6.0,<4.7"
ipykernel = ">=7.2.0,<8"
tqdm = ">=4.67.3,<5"

[pypi-dependencies]
scimap = "==2.3.6"
